---
title: "Summary"
author: "Curso de Estadística Descriptiva"
date: "26/12/2018"
output: html_document
---
## Summary

```{r}
by(iris[,c(1,3)], iris$Species, FUN = summary)
str(iris)

boxplot(iris[,-1])
boxplot(Sepal.Length~Species, data=iris)
boxplot(Sepal.Length~Species, data=iris, notch=T)
points(mean, col='darkred', pch=21)

str(boxplot(Sepal.Length~Species, data=iris))
boxplot(Sepal.Length~Species, data=iris)$out
boxplot(Sepal.Length~Species, data=iris)$group

mean= aggregate(Sepal.Length~Species, data = iris, FUN = mean)

```


```{r}
aggregate(cbind(Sepal.Length,Petal.Length)~Species, 
          data=iris, FUN=summary)
```

# Working with NA's`

```{r}

x = c(1,2,3,NA)
sum(x)
sum(x, na.rm = TRUE)
mean(x)
mean(x, na.rm = TRUE)
var(x)
var(x, na.rm = TRUE)
sd(x)
sd(x, na.rm = TRUE)
```


```{r}
# valores minimos y maximos
range()

# rango

diff(range())

# rango interquartil
IQR()

# varianza muestral
var()

# desviavion standard
sd()

# varianza verdadera
n = length()
var()*(n-1)/n

# desfiacion verdadera
sd()*sqrt((n-1)/n)

```


```{r}
data = read.table('../../data/datacrab.txt', header = T)
summary(data)
str(data)

summary(subset(data, color==3, c('weight','spine')))
```


